sudo: required
services:
  - docker

before_install:
  - docker build -t paihari/docker-react-ci-aws -f Dockerfile.dev .

script:
  - docker run paihari/docker-react-ci-aws npm run test -- --coverage


