FROM node:alpine

WORKDIR '/app'

COPY package.json .

RUN npm install

COPY . .

CMD ["npm", "run", "start"]


#Docker Volune
#docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app <imageid>

#Docker run test
#docker run -it <imageId> npm run test


